// Espelha o picklist do custom field "Nicho específico" (opportunity.subnicho)
// na location SEED do GHL. Manter em sincronia manualmente se o field mudar lá.
export const NICHO_ESPECIFICO_OPTIONS: string[] = [
  "Aditivos Alimentares (Nutrição Animal)",
  "Consultoria em Nutrição Animal",
  "Rações (Nutrição Animal)",
  "Suplementos Nutricionais (Nutrição Animal)",
  "Adubos Orgânicos e Corretivos (Nutrição Vegetal)",
  "Defensivos Agrícolas (Nutrição Vegetal)",
  "Fertilizantes (Nutrição Vegetal)",
  "Sementes (Nutrição Vegetal)",
  "Colheitadeiras (Maq/Eqp)",
  "Implementos (Maq/Eqp)",
  "Plantadeiras/Semeadoras (Maq/Eqp)",
  "Pulverizadores (Maq/Eqp)",
  "Tratores (Maq/Eqp)",
  "Secadores/Silos (Maq/Eqp)",
  "Assistência Técnica Especializada (Serviços)",
  "Consultoria Agrícola Técnica (Serviços)",
  "Consultoria em Tecnologia de Aplicação (Serviços)",
  "Pesquisa Aplicada e Desenvolvimento (Serviços)",
  "Serviços de Agricultura de Precisão (Serviços)",
  "Crédito Rural (Fin/Seg)",
  "Gestão de Risco (Fin/Seg)",
  "Seguro Agrícola (Fin/Seg)",
  "Seguros Complementares (Fin/Seg)",
  "Agriculture de Precisão (Software)",
  "ERP Agrícola (Software)",
  "Plataformas Especializadas (Software)",
  "Bioinsumos e Produtos Biológicos (Outros)",
  "Logística e Transportes (Outros)",
  "Sementes e Mudas (Outros)",
  "Advogado (Outros)",
  "Energia Solar/Geradores (Outros)",
  "Outros",
];
